# Generated by Django 5.1.1 on 2026-03-02 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre Producto')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto Producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
