# Generated by Django 5.1.1 on 2026-03-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caducidad',
            field=models.BooleanField(default=False, verbose_name='¿El producto tiene fecha de caducidad?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Granos', 'Granos'), ('Lácteos', 'Lácteos'), ('Carnes', 'Carnes'), ('Otros', 'Otros')], default='Otros', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de elaboración'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Lt', 'Litros'), ('Lb', 'Libras'), ('N/A', 'Sin medida'), ('Und', 'Unidad')], default='N/A', max_length=50, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción del producto'),
        ),
    ]
