# Generated by Django 5.1.1 on 2026-03-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_producto_estado_producto_producto_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen_producto',
        ),
    ]
