# Generated by Django 5.1.1 on 2026-03-04 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0007_producto_productor_alter_producto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='user',
        ),
    ]
