# Generated by Django 5.1.1 on 2026-03-04 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_remove_producto_user'),
        ('Usuario', '0007_alter_creacionusuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productor', to='Usuario.creacionproductor'),
        ),
    ]
