# Generated by Django 6.0.3 on 2026-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0009_alter_producto_productor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Granos', 'Granos'), ('Lácteos', 'Lácteos'), ('Otros', 'Otros')], default='Otros', max_length=20, verbose_name='Categoría'),
        ),
    ]
