# Generated by Django 5.1.1 on 2026-03-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='despachado',
            field=models.BooleanField(default=False),
        ),
    ]
