# Generated by Django 5.1.1 on 2026-02-23 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Departamento', models.CharField(max_length=100, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(max_length=50, verbose_name='Tipo de Identificación')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='CreacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('telefono_1', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('telefono_2', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alterno')),
                ('direccion_residencia', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias/', verbose_name='Fotografía')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.departamento')),
                ('tipo_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.identificacion')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.municipio')),
            ],
        ),
    ]
