# Generated by Django 5.1.1 on 2026-02-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionusuario',
            name='fotografia',
            field=models.ImageField(blank=True, default='usuarios/usuario_default.png', null=True, upload_to='usuarios/', verbose_name='Fotografía'),
        ),
    ]
