# Generated by Django 5.1.1 on 2026-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_creacionusuario_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionusuario',
            name='numero_identificacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación'),
        ),
    ]
