# Generated by Django 5.1.1 on 2026-03-01 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_creacionusuario_numero_identificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreacionProductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finca', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('vereda', models.CharField(blank=True, max_length=255, verbose_name='Veredales')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('foto_finca', models.ImageField(blank=True, default='productores/finca_default.png', null=True, upload_to='productores/', verbose_name='Fotografía')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
