# Generated by Django 5.1.1 on 2026-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_creacionproductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacionproductor',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción de la finca'),
        ),
    ]
