# Generated by Django 5.1.1 on 2026-03-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_creacionproductor_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionproductor',
            name='foto_finca',
            field=models.ImageField(blank=True, null=True, upload_to='productores/', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Fotografía'),
        ),
    ]
