# Generated by Django 5.1.1 on 2026-03-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_alter_creacionusuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionproductor',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.departamento'),
        ),
        migrations.AlterField(
            model_name='creacionproductor',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de la finca'),
        ),
        migrations.AlterField(
            model_name='creacionproductor',
            name='latitud',
            field=models.FloatField(null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='creacionproductor',
            name='longitud',
            field=models.FloatField(null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='creacionproductor',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.municipio'),
        ),
        migrations.AlterField(
            model_name='creacionproductor',
            name='vereda',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vereda'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.departamento'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='direccion_residencia',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.municipio'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='telefono_1',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Alterno'),
        ),
        migrations.AlterField(
            model_name='creacionusuario',
            name='tipo_identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.identificacion'),
        ),
    ]
