# Generated by Django 6.0.3 on 2026-03-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_alter_creacionproductor_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacionusuario',
            name='verificado',
            field=models.BooleanField(default=True, verbose_name='Correo verificado'),
        ),
    ]
