# Generated by Django 6.0.3 on 2026-03-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_creacionusuario_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionusuario',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Correo verificado'),
        ),
    ]
