"""
Django settings for Vanagro_Ecomerce project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#3hme&y+nwbtt87ymiu7yj&!5zw$7$df@&6fpk1$yegaefe8y&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Home.apps.HomeConfig',
    'Usuario.apps.UsuarioConfig',
    'Producto.apps.ProductoConfig',
    'Carrito.apps.CarritoConfig',
    'Pedido.apps.PedidoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Vanagro_Ecomerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #conexión con la carpeta media
                'django.template.context_processors.media',
                'Carrito.context_processors.carrito_total',
            ],
        },
    },
]

WSGI_APPLICATION = 'Vanagro_Ecomerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'base_Vanagro.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-CO'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

# Redireccionamiento después de no ser autenticado
LOGIN_URL = 'inicio'
LOGOUT_REDIRECT_URL = 'inicio'
LOGIN_REDIRECT_URL = 'sesion_inicio'

# Tiempo en segundos (ejemplo 5 minutos)
SESSION_COOKIE_AGE = 300  

# Cerrar sesión cuando el navegador se cierre
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Resetear tiempo si el usuario sigue activo
SESSION_SAVE_EVERY_REQUEST = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Ruta absoluta de la carpeta static
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Ruta absoluta para cargar archivos por parte del usuario
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuracion para la recuperacion del correo por medio de consola virtual
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# PASSWORD_RESET_COMPLETE_URL = 'login'
#Expiración del enlace para recuperar contraseña
PASSWORD_RESET_TIMEOUT = 300

# Esto es importación de os, sirve para cambiar el modo de enviar correos ficticios o reales según lo determinado en consola
DEBUG_EMAIL = os.getenv("DEBUG_EMAIL", "smtp")
# Para mostrar en consola se debe de colocar en la terminal 
# set DEBUG_EMAIL=console y luego python manage.py runserver
if DEBUG_EMAIL == "console":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    # Para que sea envio real coloca solo python manege.py runserver
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

#manejo del correo electrónico para recuperar la contraseña
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Cuenta desde donde se envían los correos, esto según el superusuario creado
# En la terminal convocar las variables ya sea set o export
# set EMAIL_USER=tucorreo@gmail.com
# set EMAIL_PASSWORD=tu_clave
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
# EMAIL_HOST_USER = 'tucorreo@gmail.com'
# Contraseña para aplicaciones que se configura con gmail
# EMAIL_HOST_PASSWORD = 'laclave'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

