# Generated by Django 5.1.1 on 2026-02-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=70, verbose_name='Apellido')),
                ('telefono', models.PositiveBigIntegerField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('mensaje', models.TextField(verbose_name='Su mensaje')),
            ],
        ),
    ]
