# Generated by Django 5.1.1 on 2026-02-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado del mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envió'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='telefono',
            field=models.PositiveBigIntegerField(verbose_name='Teléfono'),
        ),
    ]
