# Generated by Django 5.1.1 on 2026-03-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_mensaje_estado_alter_mensaje_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='apellido',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='apellidos',
            field=models.CharField(default='prueba', max_length=70, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='prueba', max_length=150, verbose_name='Asunto'),
            preserve_default=False,
        ),
    ]
