# Generated by Django 5.1.1 on 2026-03-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_mensaje_atendido_por_mensaje_respuesta_mensaje_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
