# Generated by Django 6.0.3 on 2026-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_mensaje_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(max_length=500, verbose_name='Su mensaje'),
        ),
    ]
