# Generated by Django 6.0.3 on 2026-04-08 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_mensaje_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Su mensaje'),
        ),
    ]
